import type { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  return knex.schema.table('users', (table) => {
    table
      .integer('token_version')
      .notNullable()
      .defaultTo(0)
      .comment(
        'To keep track of the tokens (email verification, forgot pass etc) generated by user and to revoke the tokens if needed',
      );
  });
}

export async function down(knex: Knex): Promise<void> {
  return knex.schema.table('users', (table) => {
    table.dropColumn('token_version');
  });
}
